export const ROUTE_NAMES = Object.freeze({
  HOME: 'home',
  LOGIN: 'login',
  OAUTH_CALLBACK: 'oauth-callback',
  BROKER_CONNECT: 'broker-connect',
  BROKER_VERIFY: 'broker-verify',
  PORTFOLIO: 'portfolio',
  MYPAGE: 'mypage',
  MYPAGE_EDIT: 'mypage-edit',
  MYPAGE_ACCOUNTS: 'mypage-accounts',
  JOURNAL: 'journal',
  JOURNAL_CREATE: 'journal-create',
  AI_CONVERSATION: 'ai-conversation',
  UI_KIT: 'ui-kit',
  NOT_FOUND: 'not-found',
})
